### PR TITLE
Introduce Docker image

### PR DESCRIPTION
**Pull request by Macleykun**
Fufills partly https://github.com/ZNielsen/PodRacer/issues/51

This PR adds the CI/CD and Dockerfile to host the docker image so users can run PodRacer using docker (using only one command)!

## However i'm currently stuck as the compiler seems to panic:
https://github.com/Macleykun/PodRacer/actions/runs/3721946309/jobs/6312442673

If that can be resolved somehow, the following has to be done:

- [ ] Build the image successfully
- [ ] Test if it works
- [ ] Answer questions how it works and why/what i did
- [ ] Let maintainer decide wheter to use Dockerhub to GitHub to host the docker image and edit the workflow accordingly
- [ ] Write/edit README how to run this
- [ ] Let maintainer set the right Action secrets so the workflow will work after merging

### CODE REVIEW

**Comment by ZNielsen** [comment]
I checked out this branch to test. Rebased it over main to pick up the change to stable + removed the switch to nightly from the dockerfile. Looks like there's still some directory setup to be done. Result of a docker run:

```
    Finished release [optimized] target(s) in 0.25s
     Running `target/release/podracer`
Error: FileServer path '/etc/podracer/config/server/web/static' is not a directory.
   >> Aborting early to prevent inevitable handler failure.
thread 'main' panicked at 'invalid directory: refusing to continue', server/src/main.rs:77:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Macleykun** [comment]
I've come to the same error aswell, however i'm not sure how to exactly resolve it.
I could create the folder myself, however i assume podracer creates these web files itself?

**Comment by martadinata666** [comment]
It manually created or symlinked
* https://github.com/ZNielsen/PodRacer/blob/main/service_files/how_to.md

And looking on the systemd script, also need set `ROCKET_CONFIG` path.

**Comment by Macleykun** [comment]
so the latest build worked, i can't test it out right away but if someone can test it meanwhile: macley/oled_stats
if it works, i'll optimize it

**Comment by martadinata666** [comment]
tried your image.
```
Error: Rocket configuration extraction from provider failed.
   >> unexpected character found: `%` at line 43 column 26
   >> in Rocket.toml TOML file

```
oh my bad, after lookin around the "%" accidentally chimmed it. As `Rocket.toml` i prefer that upstream, update it or someway override the template path 🤔 or well use upstream path at 
* `server/web/static`
* `server/web/templates`
It just adding a subdir. ❤️

**Comment by Macleykun** [comment]
Great news! it's working :)
image
I do hope the way i changed the rocket.toml is acceptable.

I'll look tommorow (or later next week, but this year for sure!) to optimize the dockerfile.

Are there any folders/files that recieve changes that need to be persistant? Then i know what to write down for the volumes and can also work on making it rootless.

Try it out with:
```
docker pull macley/oled_stats && docker run --network=host --name podracer --rm macley/oled_stats`
```

**Comment by Macleykun** [comment]
I optimized it and it’s also running rootless.
Are there directories that need to be persistent? And would you prefer to host on dockerhub or GitHub registert for the docker images?

**Comment by Macleykun** [comment]
Had some strange issue with armV7, but it's fixed now and they all are now compiling all 3 :)
Only need to know what folders need to be persistant so i can formulate the run command and write docs and make it ready for merge.

**Comment by Macleykun** [comment]
So i have the docs ready, however when i tested the app i noticed this error:
```
Success creating feed!
thread 'rocket-worker-thread' panicked at 'Failed to overwrite file: Os { code: 18, kind: CrossesDevices, message: "Invalid cross-device link" }', racer/src/lib.rs:1299:6
   >> Handler create_feed_handler panicked.
   >> A panic is treated as an internal server error.
   >> No 500 catcher registered. Using Rocket default.
```
It did create the right subfolder:
image
image

You have any clue what might be going wrong?

**Comment by ZNielsen** [comment]
> Invalid cross-device link

Looks like this is an issue with using rename vs move. Rename can't be done across filesysems.

https://stackoverflow.com/a/43967659

Sounds like there either needs to be an assurance that renames within the docker container are on the same volume, or the call in the application needs to change. 
Feels like the application change is the right call, I'll look into it. I haven't had much time to look at anything over the holidays, so it may be a bit.

**Comment by Macleykun** [comment]
> > Invalid cross-device link
> 
> Looks like this is an issue with using rename vs move. Rename can't be done across filesysems.
> 
> https://stackoverflow.com/a/43967659
> 
> Sounds like there either needs to be an assurance that renames within the docker container are on the same volume, or the call in the application needs to change. Feels like the application change is the right call, I'll look into it. I haven't had much time to look at anything over the holidays, so it may be a bit.

no worries fam! And yea it's on a different volume, that way we can make the podcasts folder persistent between updates :).
And take ya time, no rush to get it done within this year :)

 Also, would you prefer to host the images on dockerhub or github registery?

**Comment by ZNielsen** [comment]
> dockerhub or github registery
I have never been exposed to either of those. I'll look into it.

**Comment by ZNielsen** [comment]
With a cursory look I'm leaning towards GitHub registry, however it's not 100% clear to me when the data limits apply. 
I'm not going to pay to host this. Does the 1GB limit mean if the image is 100MB, it could only be downloaded 10x a month?
Additional transfer is $0.50/GB. Is there a way to configure it to not transfer once the limit is reached? I don't want someone's rogue script to cost me 3-4 figures.

**Comment by ZNielsen** [comment]
> > > Invalid cross-device link

This should now be fixed on mainline

**Comment by Macleykun** [comment]
> With a cursory look I'm leaning towards GitHub registry, however it's not 100% clear to me when the data limits apply. I'm not going to pay to host this. Does the 1GB limit mean if the image is 100MB, it could only be downloaded 10x a month? Additional transfer is $0.50/GB. Is there a way to configure it to not transfer once the limit is reached? I don't want someone's rogue script to cost me 3-4 figures.

https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages
So it's completely free for public packages, it's only paid once ya cross the free tier for private packages :)

I'll switch to github registery, just to see how it works and if everything checks out and all.

**Comment by Macleykun** [comment]
> > > > Invalid cross-device link
> 
> This should now be fixed on mainline

thanks it works now :D 
image

**Comment by Macleykun** [comment]
docker pull ghcr.io/macleykun/podracer:latest
works :)
So i believe everything is now ready for merging, you do need to set a secret in the actions in settings of your repo.
This has to be named: TOKEN
and the value needs to be your github account password.

It'll take 2 hours to let the CI/CD finish, but you can also just do amd64 as that one only needs 15 minutes or so:
https://github.com/Macleykun/PodRacer/actions/runs/3809209834

You can see the package/image here:
https://github.com/Macleykun/PodRacer

You'll always push to latest whenever you manually trigger it in the actions tab. This is done b/c again the CI/CD takes 2 hours and i think it's wiser to let you decide when to run that.

Feel free to use this PR after it's merged for questions or any problems you may have.
Happy 2023 :D

**Review by ZNielsen — APPROVED** [review]

**Pull request merged**
